#!/bin/python
import imaplib
mail = imaplib.IMAP4_SSL('imap.EXAMPLE.COM')
mail.login('USERNAME', 'PASSWORD')
mail.select("inbox") # connect to inbox.
if (len(mail.search(None, 'UNSEEN')[1][0].split())) > 0:
    print (" " + str(len(mail.search(None, 'UNSEEN')[1][0].split())))
