#!/bin/bash

IF=$(ip route | awk '/^default/ { print $5 ; exit }')

if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo   # full text
  echo   # short text
  echo \#FF3333 # color
  exit
fi

# if default route via wifi
if [[ $(echo $IF | tr -d 0-9) = "wlps" ]] ; then
    QUALITY=$(grep $IF /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    SSID=$(iwgetid -r)
    echo " $SSID $QUALITY%" # full text
    echo " " # short text

    if [[ $QUALITY -lt 40 ]]; then
        echo "#FF3333" # color
    else
        echo "#FFFFFF"
    fi

fi

# if default route via lan
case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

# if no interface is found, use the first device with a global scope
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

if [[ -z $IPADDR ]]; then
  echo   # full text
  echo   # short text
  echo \#FF3333 # color
  exit
fi

echo "  [$IPADDR]" # full text
echo " " # short text
echo "#FFFFFF"
